### ISSUE TITLE
使用DNS功能出现问题

### ISSUE THREAD

**Issue by Ivaneus** [hulisang/v2ray-sspanel-v3-mod_Uim-plugin#4]
使用DNS的时候 如果按照给出的docker run写法 会把DNS当做docker image进行update 如果换成rico给出的 -e dns=xxx的类似写法 docker可以运行 但是日志报错 节点无法连接

**Comment by hulisang** [comment]
是的，试试用dev的脚本安装

**Comment by hulisang** [comment]
最新dev应该解决了，用hulisang/v2ray_v3:go_pay这个镜像
