### ISSUE TITLE
dev版报错

### ISSUE THREAD

**Issue by shigalin** [hulisang/v2ray-sspanel-v3-mod_Uim-plugin#7]
v2ray_1  | (/root/go/src/github.com/rico93/v2ray-sspanel-v3-mod_Uim-plugin/db/ssrpanel.go:99) 
v2ray_1  | [2020-03-07 23:13:06]  Error 1054: Unknown column 'vmess_id' in 'field list' 
v2ray_1  | 2020/03/07 23:13:06 [Warning] SSPanelPlugin: initial system
v2ray_1  | 2020/03/07 23:13:06 [Warning] SSPanelPlugin: Plugin Running ERROR > SSPanelPlugin: Getting Userinfo Failed  > Error 1054: Unknown column 'vmess_id' in 'field list'

**Comment by hulisang** [comment]
对接的是ssrpanel吗，我这里测试sspanel没有问题

**Comment by shigalin** [comment]
嗯，是魔改那个，您这边是哪个面板，项目地址联系给我一个看看可以么。

**Comment by hulisang** [comment]
我用的这个版本 https://github.com/GeekQu/ss-panel-v3-mod_Uim

**Comment by shigalin** [comment]
好的，谢谢
